{
  description = "delus default dev shell";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  };

  outputs = { self, nixpkgs }:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs { inherit system; };
    in {
      devShells.${system} = {
        default = pkgs.mkShell {
          name = "delus-dev";

          packages = with pkgs; [
            # core
            git
            gh
            curl
            wget
            jq
            yq-go

            # search / nav
            ripgrep
            fd
            bat
            eza
            fzf
            tree

            # languages / runtimes
            python313
            uv
            nodejs_22
            go

            # build
            gnumake
            gcc
          ];

          shellHook = ''
            echo "delus dev shell — $(nix --version)"
            echo "tools: $(python3 --version 2>&1), $(node --version), $(go version | cut -d' ' -f3)"
          '';
        };

        glm = pkgs.mkShell {
          name = "glm";

          packages = with pkgs; [
            nodejs_22
            uv
            git
            curl
            jq
          ];

          shellHook = ''
            # Marker: tells ~/.zshrc to skip conda init so uv python wins on PATH
            export IN_GLM_SHELL=1

            # Force SHELL back to the user's real zsh. Otherwise `nix develop`
            # sets SHELL to its own minimal bash, and tmux (which reads SHELL
            # for default-shell) spawns broken bash panes that can't source
            # ~/.bashrc cleanly.
            if [ -x /usr/bin/zsh ]; then
              export SHELL=/usr/bin/zsh
            elif command -v zsh >/dev/null 2>&1; then
              export SHELL="$(command -v zsh)"
            fi

            # Claude config lives in a dedicated dir for the GLM-backed setup
            export CLAUDE_CONFIG_DIR="$HOME/.claude-glm"
            mkdir -p "$CLAUDE_CONFIG_DIR"

            # Auto-load env vars from ~/.claude-glm/.env if present
            if [ -f "$CLAUDE_CONFIG_DIR/.env" ]; then
              set -a
              . "$CLAUDE_CONFIG_DIR/.env"
              set +a
              echo "loaded env from $CLAUDE_CONFIG_DIR/.env"
            else
              echo "note: $CLAUDE_CONFIG_DIR/.env not found — create it to auto-load vars"
            fi

            # Shell-local npm prefix — global installs live here, not in ~/.npm-global
            export NPM_CONFIG_PREFIX="$CLAUDE_CONFIG_DIR/npm"
            export PATH="$NPM_CONFIG_PREFIX/bin:$PATH"
            mkdir -p "$NPM_CONFIG_PREFIX"

            # ccm: claude with permission checks bypassed (function so "$@" works)
            ccm() { claude --dangerously-skip-permissions "$@"; }
            export -f ccm 2>/dev/null || true

            # Custom ZDOTDIR so we can inject glm-only zsh aliases without
            # touching the user's ~/.zshrc. The wrapper .zshrc sources the
            # real one first, then adds glm-specific aliases/functions.
            export ZDOTDIR="$CLAUDE_CONFIG_DIR/zsh"
            mkdir -p "$ZDOTDIR"
            cat > "$ZDOTDIR/.zshrc" <<'ZEOF'
# Auto-generated by the glm nix devShell — do not edit by hand.
# Sources the user's real startup files, then layers glm-only aliases.

[ -f "$HOME/.zshenv" ] && . "$HOME/.zshenv"
[ -f "$HOME/.zshrc"  ] && . "$HOME/.zshrc"

# --- glm-only aliases ---
alias tmg='tmux -L glm'
ZEOF

            echo "glm shell ready"
            echo "  node:              $(node --version)"
            echo "  CLAUDE_CONFIG_DIR: $CLAUDE_CONFIG_DIR"
            echo "  npm prefix:        $NPM_CONFIG_PREFIX"
            echo "  ccm:               claude --dangerously-skip-permissions"
            echo "  tmg:               tmux -L glm (isolated tmux socket)"
          '';
        };
      };
    };
}
